version: '3.9'

services:
  backend:
    build: .
    container_name: django-drf-class-proj
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/core